site_name: DTU-MLOps
docs_dir: .
site_dir: ../site
repo_url: https://github.com/SkafteNicki/dtu_mlops

theme:
  language: en
  name: material
  favicon: figures/favicon.png
  logo: figures/mlops_cycle.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:skaftenicki@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/SkafteNicki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nicki-skafte-detlefsen/

nav:
  - Home: README.md
  - Timeplan: timeplan.md
  - S1 - Development Environment 💻:
    - s1_development_environment/README.md
    - M1 - The command line: s1_development_environment/command_line.md
    - M2 - Package Manager: s1_development_environment/package_manager.md
    - M3 - Editor: s1_development_environment/editor.md
    - M4 - Deep Learning Software: s1_development_environment/deep_learning_software.md
  - S2 - Organisation and Version Control 📁:
    - s2_organisation_and_version_control/README.md
    - M5 - Git: s2_organisation_and_version_control/git.md
    - M6 - Code structure: s2_organisation_and_version_control/code_structure.md
    - M7 - Good coding practice: s2_organisation_and_version_control/good_coding_practice.md
    - M8 - Data version control: s2_organisation_and_version_control/dvc.md
  - S3 - Reproduceability ♻️:
    - s3_reproducibility/README.md
    - M9 - Docker: s3_reproducibility/docker.md
    - M10 - Config Files: s3_reproducibility/config_files.md
  - S4 - Debugging, Profiling and Logging ⏱️:
    - s4_debugging_and_logging/README.md
    - M11 - Debugging: s4_debugging_and_logging/debugging.md
    - M12 - Profiling: s4_debugging_and_logging/profiling.md
    - M13 - Logging: s4_debugging_and_logging/logging.md
    - M14 - Boilerplate: s4_debugging_and_logging/boilerplate.md
  - S5 - Continues Integration ✔️:
    - s5_continuous_integration/README.md
    - M15 - Unittesting: s5_continuous_integration/unittesting.md
    - M16 - Github Actions: s5_continuous_integration/github_actions.md
    - M17 - Pre commit: s5_continuous_integration/pre_commit.md
    - M18 - Continues Containers: s5_continuous_integration/auto_docker.md
    - M19 - Continues Machine Learning: s5_continuous_integration/cml.md
  - S6 - The cloud 🌐:
    - s6_the_cloud/README.md
    - M20 - Cloud Setup: s6_the_cloud/cloud_setup.md
    - M21 - Using the Cloud: s6_the_cloud/using_the_cloud.md
  - S7 - Deployment 📦:
    - s7_deployment/README.md
    - M22 - Requests and APIs: s7_deployment/apis.md
    - M23 - Local Deployment: s7_deployment/local_deployment.md
    - M24 - Cloud Deployment: s7_deployment/cloud_deployment.md
  - S8 - Monitoring 📊:
    - s8_monitoring/README.md
    - M25 - Data Drifting: s8_monitoring/data_drifting.md
    - M26 - System Monitoring: s8_monitoring/monitoring.md
  - S9 - Scalable applications ⚖️:
    - s9_scalable_applications/README.md
    - M27 - Distributed Data Loading: s9_scalable_applications/data_loading.md
    - M28 - Distributed Training: s9_scalable_applications/distributed_training.md
    - M29 - Scalable Inference: s9_scalable_applications/inference.md
  - S10 - Extra 🔥:
    - s10_extra/README.md
    - M30 - Command Line Interfaces: s10_extra/cli.md
    - M31 - Documentation: s10_extra/documentation.md
    - M32 - Hyperparameter optimization: s10_extra/hyperparameters.md
    - M33 - High Performance Clusters: s10_extra/high_performance_clusters.md
    # - M34 - Designing Pipelines: s10_extra/design.md
    # - M35 - Frontend: s10_extra/frontend.md
    # - M36 - Sharing models - ONNX format: s10_extra/onnx.md
    # - M37 - Pipeline orchestration: s10_extra/pipeline.md
    # - M38 - Kubernetes: s10_extra/kubernetes.md
  - Summary: overview.md
  - Projects: projects.md
  # - Challenges: challenges.md
  - FAQ: faq.md
